Some general comments on README
LeapMind/bluegrass pull request #5
Opened 2020-07-21 17:37 UTC by hariby

I put some general comments on 2 DE10-Nano devices setup as in PR https://github.com/LeapMind/bluegrass/pull/2. 
(A single-device instruction is moved to another branch.)

2020-09-07 06:58 UTC, hadusam requested changes
@hariby 
Sorry for the late response 🙇 
Thanks for your suggestions!
Almost LGTM, I left one comment, please check it! 👍

2020-09-07 06:58 UTC, hadusam commented on deploy/sagemaker.yaml
> +        - Content: 'IyEvYmluL2Jhc2gKc3VkbyAtdSBlYzItdXNlciAtaSA8PCdFT0YnCmNkIC9ob21lL2VjMi11c2VyL1NhZ2VNYWtlciAmJiBnaXQgY2xvbmUgaHR0cHM6Ly9naXRodWIuY29tL0xlYXBNaW5kL2JsdWVncmFzcy5naXQKRU9G'
@hariby 
I think this setting is for cloning our repository as default.
How about using `DefaultCodeRepository` to clone our bluegrass repository? I think it is enough and suitable for this use.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-notebookinstance.html#cfn-sagemaker-notebookinstance-defaultcoderepository

2020-09-07 07:16 UTC, hadusam commented on README.md
> +certificateArn is "arn:aws:iot:ap-northeast-1:123456789012:cert/xxxxxx...xxxxxx"
NIT: Do we need to change this line? I think the value of `ap-northeast-1:123456789012` depends by the user's environment.

2020-09-07 07:17 UTC, hadusam commented on README.md
> +Run commands below, where `MODEL_S3_URI` will be set as a form of `s3://sagemaker-ap-northeast-1-123456789012/blueoil-sagemaker-2020-XX-XX-XX-XX-XX-XXZ/output/converted/output.tar.gz`.
```suggestion
Run commands below, where `MODEL_S3_URI` will be set as a form of `s3://sagemaker-xxxxxx/blueoil-sagemaker-2020-XX-XX-XX-XX-XX-XXZ/output/converted/output.tar.gz`. 
```

Same.
> NIT: Do we need to change this line? I think the value of ap-northeast-1:123456789012 depends by the user's environment.

2020-10-10 16:00 UTC, hariby commented
Revised according to the comments from @hadusam, thanks.

2020-10-13 01:06 UTC, hadusam reviewed
@hariby 
Thanks for updating!
LGTM except for one additional comment.
Could you check it? Thanks 😄

2020-10-13 01:06 UTC, hadusam commented on deploy/create_cert.sh
> +aws iot create-keys-and-certificate --set-as-active --certificate-pem-outfile "cert.pem" --public-key-outfile "public.key" --private-key-outfile "private.key" | tee cert_result.log > /dev/null
Is it a problem to output stdout? This line (using `tee`) is intentional to display the standard output of this command.

2020-10-26 14:33 UTC, hariby commented
@hadusam Thank you for your comment!

2020-12-09 02:47 UTC, hadusam approved these changes
Sorry for the late review:bow:
LGTM,Approval:+1:

2020-12-09 02:48 UTC, merged